name: blue_crab
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  table_calendar: ^3.0.9
  equatable: ^2.0.5
  dio: ^5.3.3
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  slang: ^3.25.0
  slang_flutter: ^3.25.0
  auto_route: ^7.8.4
  get_it: ^7.6.4
  font_awesome_flutter: ^10.6.0
  flutter_colorpicker: ^1.0.3
  flutter_local_notifications: ^16.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  slang_build_runner: ^3.25.0
  auto_route_generator: ^7.3.2
  hive_generator: ^2.0.1
  talker_flutter: ^3.5.2
  talker_dio_logger: ^2.3.1
  talker_bloc_logger: ^2.2.1
  talker: ^3.1.4

flutter:
  uses-material-design: true

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/rubik/Rubik-Black.ttf
          weight: 900

        - asset: assets/fonts/rubik_italic/Rubik-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/rubik_italic/Rubik-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/rubik_italic/Rubik-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/rubik_italic/Rubik-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/rubik_italic/Rubik-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/rubik_italic/Rubik-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/rubik_italic/Rubik-BlackItalic.ttf
          style: italic
          weight: 900

  assets:
    - assets/icons/